loadTimeData.data = {
  bestScore: "Best $1 $2 $3",
  bestScoreFlyout: "Best score: $1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "Cancel",
  close: "Close",
  code: "Cheat code activated!",
  codeCheat: "Cheat code activated! $1",
  codeScoring: "Scoring turned off for this round.",
  endlessBestScore: -1,
  endlessDescriptor: "distance",
  endlessModeTitleInline: "Endless:",
  endlessTitle: "3 Meses",
  endlessUnit: "m",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "Game credits",
  gameCreditsDialogTitle: "Game credits",
  gameMode: "Game mode changed to $1",
  gameModeSelectLabel: "Game mode",
  gameModeSelectLabelDisabled: "Game mode (start new game to change)",
  gameSettings: "Game settings",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "High visiblity",
  howToPlayButton: "Como Jogar",
  howToPlayControllerBoost: "Pressione RT para usar seu aumento de velocidade",
  howToPlayControllerMovement: "Use o thumbstick ou D-pad para jogar",
  howToPlayControllerRefresh: "Pressione LB+RB para reiniciar o jogo",
  howToPlayDialogTitle: "Como Jogar",
  howToPlayEndless:
    "Viaje o mais longe que puder e resgate um amigo para ajudar com os inimigos",
  howToPlayKeyboardBoost: "Pressione `F` para usar o aumento de velocidade",
  howToPlayKeyboardMovement: "Use as setas ou as teclas `WASD` para jogar",
  howToPlayKeyboardRefresh: "Atualize a página para reiniciar o jogo",
  howToPlayMouseBoost: "Clique com o botão direito para usar o aumento de velocidadet",
  howToPlayMouseMovement: "Mova o mouse para jogar",
  howToPlayMouseRefresh: "Atualize a página para reiniciar o jogo",
  howToPlayTimeTrial:
    "Chegue ao fim o mais rápido que puder e colete moedas para subtrair o tempo",
  howToPlayTouchBoost: "Deslize para baixo duas vezes para usar o aumento de velocidade",
  howToPlayTouchMovement: "Deslize ou toque para jogar",
  howToPlayTouchRefresh: "Atualize a página para reiniciar o jogo",
  howToPlayZigZag: "Passe por quantos portões você puder em sequência",
  is_windows_xbox_sku: "false",
  keyboardAction: "spacebar",
  language: "pt",
  lastSelectedMode: "endless",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "ski",
  menuInfo: "Iniciar",
  mouseAction: "double click",
  newBestScore: "New best $1 $2 $3",
  newGame: "Jogar Novamente",
  off: "Off",
  on: "On",
  overInfo: "para jogar novamenten",
  overTitle: "Boa tentativa!",
  pauseInfo: "para retomar o jogo",
  pauseTitle: "Jogo pausado",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "Velocidade reduzida",
  resetAllStats: "Redefinir todas as estatísticas",
  resetAllStatsDialogText:
    "Tem certeza de que deseja redefinir todas as estatísticas do jogo, incluindo suas pontuações mais altas?",
  resetAllStatsDialogTitle: "Redefinir todas as estatísticas",
  share: "Compartilhe com um amigo",
  shareCopy: "Copy",
  shareLink: "edge://surf",
  shareLinkCopied: "Copiado!",
  skiTheme: "Esqui de Joana",
  specialThanks: "Agradecimentos especiais:",
  surfTheme: "Esqui de Joana",
  textdirection: "ltr",
  theme: "Theme changed to $1",
  themeSelectLabel: "Theme",
  timetrialBestScore: -1,
  timetrialDescriptor: "time",
  timetrialModeTitleInline: "Teste contra-relógio:",
  timetrialTitle: "Contra-relógio",
  timetrialUnit: "s",
  touchAction: "toque duplo",
  zigzagBestScore: -1,
  zigzagDescriptor: "streak",
  zigzagModeTitleInline: "Zig zag:",
  zigzagTitle: "Zig zag",
  zigzagUnit: "gates",
};
